### ISSUE TITLE
[Anon] Bug report: Codex - Chaos.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-2nd-edition#1]
**File:** Codex - Chaos.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Chaos terminators "Chain axe" has been given the same stats as a "Power Mace".

**Comment by Boff89** [comment]
fixed in latest update! Going out today, thank you for that
