### ISSUE TITLE
[Anon] Codex - Orks: Ork Dreadnought displays error. Ork Dreadnought should be allowed if painboy is in army list, but an alert appears.

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/wh40k-2nd-edition#10]
**Problem:**
Ork Dreadnought displays error. Ork Dreadnought should be allowed if painboy is in army list, but an alert appears.

**Expected:**
Ork Dreadnought should be allowed when a painboy is in the army.

**List:** https://www.newrecruit.eu/app/list/qYYcY

**Comment by Boff89** [comment]
Hello,

In 2nd ed Ork Codex you need both a painboy AND a mekboy to bring the dreadnought. But if that changed somewhere in FAQ etc please let me know. Attached photo from dex
![image](https://github.com/user-attachments/assets/35ec284c-88a8-4798-9495-16e746cd6c34)
