### ISSUE TITLE
[Anon] Codex - Ultramarines: When Selecting Terminator heavy weapons it assigns to all models instead of 1

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/wh40k-2nd-edition#11]
**Problem:**
When Selecting Terminator heavy weapons it assigns to all models instead of 1

**Expected:**
It should allow assignment to 1 terminator only

**List:** https://www.newrecruit.eu/app/list/Ouwym

**Comment by Boff89** [comment]
Issue fixed, released update now
