### ISSUE TITLE
[Anon] Codex - Angels of Deaths (Blood Angels): Too many guardsmen

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/wh40k-2nd-edition#13]
**Problem:**
Too many guardsmen

**Expected:**
Taking heavy weapon does not add 2 guardsmen to the squad.

 **Additional Info:**
Imperial guard codex page 79

**Comment by Boff89** [comment]
This will now be fixed - You should get an error when adding a heavy weapon squad and will have to remove 2 "regular" guardsman so you stay with the same total of 5 men
