### ISSUE TITLE
[Anon] Bug report: Codex - Genestealer Cults.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-2nd-edition#16]
**File:** Codex - Genestealer Cults.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Genestealer Cult Icon gets warning for selecting two many wargear cards at only two wargear cards.

**Comment by Boff89** [comment]
![image](https://github.com/user-attachments/assets/52b9e46c-488a-4618-ad7d-dbc2acb73faf)
Icon bearer can only take 1 wargear card
