### ISSUE TITLE
[Anon] Bug report: Codex - Imperial Agents.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-2nd-edition#17]
**File:** Codex - Imperial Agents.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Adeptus Arbites do not have the option to select bikes as an option for the whole squad.

**Comment by Boff89** [comment]
this seems to be from the battle bible, but the actual army list doesn't give them any options
