### ISSUE TITLE
Codex Chaos marine corrections

### ISSUE THREAD

**Issue by ausmagpie** [BSData/wh40k-2nd-edition#2]
G'day. I've noted a small number of inconsistencies in an otherwise frankly amazing project.

1) Thousand Sons Bodyguard has X too many selections of Boltgun (maximum 0) - this logic should allow as many selections of Boltgun as there members in the squad.

2) Missing Chaos Lord Wargear option - when granted the Mark of Tzeentch and a Psyker Mastery Level the character should be able to select the Psyker only Wargear cards (such as a Force Sword) in the same way a Chaos Space Marine Sorcerer is.

3) Noise Marine Squad weapon options are all zero points. These should be 
- Sonic Blaster 10 pts 
- Blastmaster 45 pts
- Doom Siren 15 pts
- Photon flash flares 5 pts

(These point values are correct for Aspiring Champions leading the squad, just not the squad members themselves)

**Device and data**
 - OS: Android 13
 - BattleScribe version v2.03.25.338
 - Release version Codex - Chaos v7 by Boff, 40k 2nd edition V1.3.4

**Comment by Boff89** [comment]
Thank you for pointing these out! I have fixed these and pushed the update now, hopefully life in a few hours.

**Comment by ausmagpie** [comment]
Wow! Legend!
