### ISSUE TITLE
Points correction: Force Sword

### ISSUE THREAD

**Issue by Badatscrabble** [BSData/wh40k-2nd-edition#3]
https://github.com/BSData/wh40k-2nd-edition/blob/9be975f3e1c9a16e7d0b1ed0734dfe0a61d7a3cf/Warhammer%2040k%202nd%20Edition.gst#L2993

Change: value to 10.0
Reason: physical card for Force Sword is marked as 10 points

**Comment by Boff89** [comment]
Thank you! I have fixed this for the next update
