### ISSUE TITLE
Source Data Correction - Warhammer 40k 2nd edition

### ISSUE THREAD

**Issue by BrotherTerran** [BSData/wh40k-2nd-edition#4]
**Describe the bug**
Incorrect Source Data for some codexes and missing codices: Not sure if you a seperate bug report for each, but here is a summary.
- Orks: not a big one, but selections are incorrect for Ghazghkull wargear, everything I can tell looks great for orks(screen shot included)
- Wargear: Rad Grenade Wargear point cost is incorrect shows "5" should be "25" (screen shot included)
- Sister of Battle: missing Character unit "Preacher" (screenshot included). However, just summarize 10 pts cost
M-4 WS-4 BS-4 S-3 T-3 W-1 I-4 A-1 LD-9, armed with laspitol, no armor, can have 1 relic, no wargear cards, gets sacred rite to unit with no bonus to roll. A Preacher may choose additional wargear from the Assault Weapons, Special Weapons, Militia Basic Weapons and Armour Wargear Lists
- Imperial Guard - there is no chapter-approved Baneblade(as much as I'd like there one to be). Reference is blank
- Imperial Guard - Command HQ Psyker option only shows the Primaris as an option not the other IG Psykers as well.(screen shot included)
- Imperial Agents Codex Missing: Adeptus Mechancus, & inquistion missing(ref Warhammer 40k box set)(screenshots of army list provided) Should be allies of imperial forces (IG, space marines, and sisters of battle)

**To Reproduce**
1. Go to '...' Character Choices
2. Click on '....' Ghazghkull 
3. Scroll down to '....' select "show wargear" select any wargear item (screenshot provided)

**Expected behavior**
![Imperial Agents - Missing 1](https://user-images.githubusercontent.com/132292796/235515413-e9bbc2a8-8fad-42b9-9038-028fe747c413.jpg)
![Imperial Agents - Missing 2](https://user-images.githubusercontent.com/132292796/235515568-2b1d05f4-7163-4ada-a3c4-4091415b3efd.jpg)

Please adjust your point cost, wargear options, and add missing unit options if possible. 

**Screenshots**
screenshots added. 

**Device and data (please complete the following information):**
 - OS: [e.g. iOS] - Windows
 - BattleScribe version [e.g. 2.03.45] - BattleScribe v2.03.21.166
 - Release version [e.g. v1.2.3] 

**Additional context**
Warhammer 40k 2nd edition data missing or needs slight correction: 

![Sisters of Battle 1- missing unit Preacher](https://user-images.githubusercontent.com/132292796/235504539-17326cbb-0afd-4317-afcd-687564fc561d.jpg)

![Ork selection error 1](https://user-images.githubusercontent.com/132292796/235501949-
![Wargear Correction 1- Rad Grenade](https://user-images.githubusercontent.com/132292796/235503696-7e04bbe5-1f62-46ba-ba25-65efb6f8baa2.png)
93ea3050-bfcf-41e7-89db-98695f145020.png)
![Imperial Agents - Missing 2](https://user-images.githubusercontent.com/132292796/235516071-faab0109-70df-4bf9-a0d2-d6b589b47014.jpg)
![Imperial Agents - Missing 3](https://user-images.githubusercontent.com/132292796/235516074-cf02c93c-9f07-4512-be93-323b4d2ba8a7.jpg)
![Imperial Agents - Missing 4](https://user-images.githubusercontent.com/132292796/235516077-e94c11b2-bab0-4f89-a408-ff0a6aed7177.jpg)
![Imperial Agents - Missing 5](https://user-images.githubusercontent.com/132292796/235516079-4da737d1-7606-46f6-8e84-bb9e4544f204.jpg)
![Imperial Agents - Missing 6](https://user-images.githubusercontent.com/132292796/235516084-c4b10761-fba1-489e-b95d-924c22d6298d.jpg)
![Imperial Guard Psyker Options](https://user-images.githubusercontent.com/132292796/235517587-f28874ed-bd80-47a5-a094-40c41fc36050.jpg)

![Imperial Agents - Missing 7](https://user-images.githubusercontent.com/132292796/235516086-79517a0b-af76-424c-837e-672ff416b7f8.jpg)
![Imperial Agents - Missing 1](https://user-images.githubusercontent.com/132292796/235516117-cb40bd6f-aa40-4cee-af6d-334c9e2a22a8.jpg)

**Comment by Boff89** [comment]
Thank you for all this work on submitting! I have fixed up all those bugs you listed, great eye! 

I have the Imperial Agents as a bit of a WIP but just hadn't gotten back to finish it off. Thanks for the inspiration to do so.

**Comment by Boff89** [comment]
The Baneblade rules I got from a combined PDF via the 40k 2nd Edition Facebook page: https://www.facebook.com/groups/851706818341637

"Datafax Collection" - Honestly not sure where they pull the Baneblade from - but as long as it gives people a chance to use it :)

**Comment by BrotherTerran** [comment]
Thanks, for correcting me. Last night I actually found the old inquistion magazine BaneBlade which I believe was official for Gamesworkshop at the time of publising. However, there are a few extra rules. such as "tank commander" and differnt point values for vehicle cards. 
![Baneblade 2nd edition](https://user-images.githubusercontent.com/132292796/236519515-d3d67853-d690-4f13-9b3f-ae84e3692cbe.jpg)

**Comment by BrotherTerran** [comment]
Keep up the great work! Thank you for all that you do.

**Comment by BrotherTerran** [comment]
Hopefully this is an easy fix, but the Sisters of Battle have an optional rule for mounted Frateris Militia bands, they didn't include it in the standard entry. 
![Screenshot 2023-05-08 205712](https://user-images.githubusercontent.com/132292796/236990370-42594046-d7d5-42bf-9648-01a73c19a71f.jpg)

**Comment by BrotherTerran** [comment]
A quick point correction for Imperial Guard Veteran point upgrade for "Guerillas" (screen shot included) currently shows as 15+, and should be 10+ pts
![IG guerilla ](https://github.com/BSData/wh40k-2nd-edition/assets/132292796/4fa764e1-fcdf-46e0-b505-1a0336ac1906)

**Comment by Boff89** [comment]
Added the mounted for Sisters codex, for those who can take it. Fixed the points for Guard vets 

Thanks again for those !

**Comment by Boff89** [comment]
Sorry haven't got to uploading it yet - I actually started work on the Imperial Agents data :). I always wondered where the screenshots came from showing the unit entries.. turns out I was missing the army book :)

**Comment by BrotherTerran** [comment]
No apologies necessary I assure you happy you have a chance to do any of it. I have basically any pages of whatever so if you want more for squats or anything I am all to happy to provide. Thank you for all that you do.

**Comment by BrotherTerran** [comment]
Great job on the update. One item if you can add it is the Graviton Gun for the Imperial Tech-Priest
![Screenshot 2023-06-15 165901](https://github.com/BSData/wh40k-2nd-edition/assets/132292796/ffa169e7-bd91-4471-995e-a1b1f460876c)

**Comment by Boff89** [comment]
Have added the Graviton Gun for the next update, thanks!

**Comment by BrotherTerran** [comment]
Found a few other items missing for Chaos on the icons. 
![Icon 1](https://github.com/BSData/wh40k-2nd-edition/assets/132292796/ea372a65-5467-4198-a149-6f420c2ed761)
![Icon 2](https://github.com/BSData/wh40k-2nd-edition/assets/132292796/5a2d41a2-40f4-438b-883a-8e10e2d7d75e)

**Comment by BrotherTerran** [comment]
I think this is more of a unit option fix I see most of the banners pop up, but undivided(non-marked chaos icon cult or chaos space marine) should had access to all icons. Also, "The Blasted Standard" seems to be missing as an option.  
The ones that do show as option are: 
![Chaos Icon - Slaanesh Mark](https://github.com/BSData/wh40k-2nd-edition/assets/132292796/bff5b44f-7724-4ecd-9896-441ee632febb)
![Chaos Icon - Nurgle Mark](https://github.com/BSData/wh40k-2nd-edition/assets/132292796/e3cdfe06-82eb-4f30-8d0f-4db83ca9a0b2)
![Chaos Icon - Khorne Mark](https://github.com/BSData/wh40k-2nd-edition/assets/132292796/9b295fcc-8b82-4e1c-8678-3886a2a9cb5c)
![Chaos Icon - No Mark](https://github.com/BSData/wh40k-2nd-edition/assets/132292796/a5c581e4-5d98-4a60-97b4-a6aedd7a4d68)
![Chaos Icon - Option Highlight](https://github.com/BSData/wh40k-2nd-edition/assets/132292796/f35c6fa1-1f88-4830-a95f-4a2fc71585c8)

**Comment by Boff89** [comment]
Been quite awhile, but I have fixed these banner issues. Thanks for pointing that out! The blasted standard confused me for a minute as I assumed it was a mark of tzeentch until I realized Icons didn't even have the options to take one lol.
