### ISSUE TITLE
[Anon] Bug report: Codex - Imperial Guard.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-2nd-edition#5]
**File:** Codex - Imperial Guard.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When selecting a psyker to join the command hq for the imperial guard codex the only option is the primaris lord, whereas there should be the 3 other levels available.

**Comment by Boff89** [comment]
Fixed this but forgot to close it, still need to upload the fix however :)
Thanks for pointing this out
