### ISSUE TITLE
Nurgle War Altar Crash

### ISSUE THREAD

**Issue by JacBoj** [BSData/wh40k-2nd-edition#6]
BattleScribe on IOS
Selecting Nurgle War Altar causes app to close down and crash. 

**To Reproduce**
1. Go to battlescribe - select 40k 2nd ed
2. Create a chaos army.
3. Ensure that two units of plague marines are added from squads (two marks of nurgle needed to unlock war altar)
4. Scroll down to support.
5. Select Nurgle War Altar which should have unlocked.
6. See error

**Expected behavior**
The app will immediately close and progress will be lost. I have tried updating the app, updating repositories and resetting device. I have tried on more than one army list. 

**Device and data (please complete the following information):**
 - OS: IoS 16.3
 - BattleScribe version [e.g. 2.03.15]
 - Release version: Unknown

**Comment by Boff89** [comment]
That's a weird one. I tried to reproduce in the browser (newrecruit), BS app on the PC and on android... but cannot reproduce this. 
I will try on an iphone later, but don't have one on hand

**Comment by JacBoj** [comment]
@Boff89 it definitely seems to be an iPhone issue then. I’ve just tried this on my wife’s IPhone and the issue is replicated. 

(Btw I had not quite appreciated that this was all your work. This project has been fantastic for me and my buddies getting back into 2nd ed! Appreciated!!!)

**Comment by Boff89** [comment]
I know this isn't truly fixed, but I suspect it's a problem with Battlescribe itself and IOS as it works fine on New Recruit... I would suggest switching if you can to that (they have an app now too I believe, not 100% for IOS tho!)
