### ISSUE TITLE
[Anon] Bug report: Codex - Tyranids.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-2nd-edition#8]
**File:** Codex - Tyranids.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** Half of the tyranids are missing for me when I try to make a army roster for tyranid

**Comment by Boff89** [comment]
Is it possible to get a screenshot of what you're seeing? I just loaded up the list and could see the units on Battlescribe
