### ISSUE TITLE
[Anon] Bug report: Codex - Imperial Agents.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-2nd-edition#9]
**File:** Codex - Imperial Agents.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Imperial guard command squad should be able to attach any level of psyker not just the master. The codex states that only the command squad can have a master psyker not that the command squad can only have a master psyker.

**Comment by Boff89** [comment]
![image](https://github.com/user-attachments/assets/4ec6b17f-831c-4191-8ee9-7c103fedc2f7)
Command squad should have the option to take any of the 3 now (and the HQ can take the Lord as well)
